services:
  mysql:
    image: mysql:8.0
    container_name: MysqlYoudemy
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: Youdemy
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminYoudemy
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8088:80"

  php:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: phpYoudemy
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "85:80"
volumes:
  mysql_data: